language: python
python:
- "3.3"
- "3.4"
- "3.5"
os:
- linux
- osx
install:
- travis_retry python setup.py develop
- travis_retry pip install pytest-cov coverage
script:
  py.test --cov=scripnix/pycommand --cov=tests --cov-report=term-missing --cov-fail-under=80
after_success:
- bash <(curl -s https://codecov.io/bash)
